"""Runner-variable injection via a generated launch wrapper.

Environment variables cannot be injected into a process a launcher starts on its
own, so ``~/.local/bin/goblin-run`` is generated instead. The user sets the game's
launch options (Steam) or command prefix (Lutris) to::

    goblin-run %command%

At launch the wrapper asks the daemon (``--print-env-for``) which variables apply
to the game being started, reads them without ``eval`` (strict ``KEY=VALUE``
lines), execs the game through ``gamemoderun`` when available, and tees the
child's stderr to ``~/.local/share/goblin-mode-pro/logs/`` for the log watcher.
"""

from __future__ import annotations

import logging
import re
from pathlib import Path

from goblinmode.config import GameProfile, Settings, slug
from goblinmode.paths import GAME_LOG_DIR, RUNNER_WRAPPER, ensure_user_dirs

log = logging.getLogger(__name__)

LAUNCH_OPTION = "goblin-run %command%"

# environment names the wrapper is permitted to set from the daemon's output
_ENV_NAME_RE = re.compile(r"^[A-Z_][A-Z0-9_]*$")
_ENV_VALUE_RE = re.compile(r"^[^\x00-\x1f\x7f]{0,4096}$")

_WRAPPER_TEMPLATE = f"""\
#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# Generated by Goblin Mode Pro - do not edit by hand.
# Regenerate: goblin-mode-pro-daemon --write-wrapper
# Usage: set your Steam launch options to   {LAUNCH_OPTION}
# ---------------------------------------------------------------------------
set -u

gmp_logdir="${{XDG_DATA_HOME:-$HOME/.local/share}}/goblin-mode-pro/logs"
mkdir -p -- "$gmp_logdir"

# Import the runner variables for this launch. No eval: each line is a strict
# NAME=VALUE that the daemon has already validated.
while IFS='=' read -r gmp_k gmp_v; do
    case "$gmp_k" in
        [A-Z_]*) export "$gmp_k=$gmp_v" ;;
    esac
done < <(goblin-mode-pro-daemon --print-env-for -- "$@" 2>/dev/null || true)

gmp_tag="$(basename -- "${{1:-game}}" | tr -cd 'A-Za-z0-9._-')"
gmp_log="$gmp_logdir/${{gmp_tag:-game}}-$(date +%Y%m%d-%H%M%S).log"

if command -v gamemoderun >/dev/null 2>&1; then
    set -- gamemoderun "$@"
fi

exec "$@" 2> >(tee -a -- "$gmp_log" >&2)
"""


def write_wrapper() -> Path:
    ensure_user_dirs()
    RUNNER_WRAPPER.write_text(_WRAPPER_TEMPLATE)
    RUNNER_WRAPPER.chmod(0o755)
    log.info("wrote launch wrapper: %s", RUNNER_WRAPPER)
    return RUNNER_WRAPPER


def _basename(token: str) -> str:
    """Basename that also splits Windows-style paths (``C:\\dir\\Game.exe``)."""
    s = token.strip().strip('"').strip("'")
    for sep in ("\\", "/"):
        if sep in s:
            s = s.rsplit(sep, 1)[-1]
    return s


def resolve_profile_for_argv(
    argv: list[str], settings: Settings
) -> GameProfile | None:
    """Find the enabled profile whose exe appears anywhere in *argv*."""
    names = {_basename(a).lower() for a in argv}
    lowered = " ".join(argv).lower()
    for profile in settings.enabled_profiles():
        if profile.match_mode == "exact" and profile.exe.lower() in names:
            return profile
        if profile.match_mode == "substring" and profile.exe.lower() in lowered:
            return profile
        if profile.match_mode == "regex":
            try:
                pat = re.compile(profile.exe[:128])
            except re.error:
                continue
            if any(pat.search(a[:4096]) for a in argv):
                return profile
    return None


def resolve_env_for_argv(argv: list[str], settings: Settings) -> dict[str, str]:
    profile = resolve_profile_for_argv(argv, settings)
    if profile is None:
        return {}
    env = dict(profile.env_assignments())
    # Make MangoHud actually load (the config file alone doesn't inject it).
    # Needed for the visible overlay AND for the frame-rate watchdog's CSV log.
    if profile.mangohud.get("enabled") or profile.fps_watchdog:
        env["MANGOHUD"] = "1"
        if profile.per_game_mangohud:
            from goblinmode.paths import MANGOHUD_DIR

            env["MANGOHUD_CONFIGFILE"] = str(MANGOHUD_DIR / f"{slug(profile.exe)}.conf")
    return env


def print_env_for(argv: list[str], settings: Settings) -> str:
    """Return validated ``NAME=VALUE`` lines for the wrapper to import (no eval).

    Names must be shell-safe identifiers and values must be single-line and
    control-character-free; anything else is dropped.
    """
    env = resolve_env_for_argv(argv, settings)
    lines = []
    for k, v in sorted(env.items()):
        if _ENV_NAME_RE.match(k) and _ENV_VALUE_RE.match(str(v)):
            lines.append(f"{k}={v}")
    return "\n".join(lines)


def latest_log_files(limit: int = 8) -> list[Path]:
    if not GAME_LOG_DIR.exists():
        return []
    logs = sorted(
        GAME_LOG_DIR.glob("*.log"), key=lambda p: p.stat().st_mtime, reverse=True
    )
    return logs[:limit]
