"""Runner-variable injection via a generated launch wrapper.

Goblin Mode Pro cannot inject environment variables into a process Steam starts
on its own, so instead it generates ``~/.local/bin/goblin-run``. The user sets
their Steam launch options to::

    goblin-run %command%

At launch the wrapper asks the daemon (``--print-env-for``) which env vars apply
to the game being started, execs it through ``gamemoderun`` when available, and
tees the child's stderr to ``~/.local/share/goblin-mode-pro/logs/`` for the log
watcher.
"""

from __future__ import annotations

import logging
import os
import shlex
from pathlib import Path

from goblinmode.config import GameProfile, Settings
from goblinmode.paths import GAME_LOG_DIR, RUNNER_WRAPPER, ensure_user_dirs

log = logging.getLogger(__name__)

LAUNCH_OPTION = "goblin-run %command%"

_WRAPPER_TEMPLATE = f"""\
#!/bin/bash
# ---------------------------------------------------------------------------
# Generated by Goblin Mode Pro - do not edit by hand.
# Regenerate from the GUI (Games page) or: goblin-mode-pro-daemon --write-wrapper
# Usage: set your Steam launch options to   {LAUNCH_OPTION}
# ---------------------------------------------------------------------------
set -u

GMP_LOGDIR="${{XDG_DATA_HOME:-$HOME/.local/share}}/goblin-mode-pro/logs"
mkdir -p "$GMP_LOGDIR"

# Ask the daemon which runner vars apply to this launch.
GMP_ENV="$(goblin-mode-pro-daemon --print-env-for "$@" 2>/dev/null || true)"
if [ -n "$GMP_ENV" ]; then
    eval "$GMP_ENV"
fi

GMP_TAG="$(basename "${{1:-game}}" | tr -cd 'A-Za-z0-9._-')"
GMP_LOG="$GMP_LOGDIR/${{GMP_TAG:-game}}-$(date +%Y%m%d-%H%M%S).log"

if command -v gamemoderun >/dev/null 2>&1; then
    set -- gamemoderun "$@"
fi

exec "$@" 2> >(tee -a "$GMP_LOG" >&2)
"""


def write_wrapper() -> Path:
    ensure_user_dirs()
    RUNNER_WRAPPER.write_text(_WRAPPER_TEMPLATE)
    RUNNER_WRAPPER.chmod(0o755)
    log.info("wrote launch wrapper: %s", RUNNER_WRAPPER)
    return RUNNER_WRAPPER


def _basename(token: str) -> str:
    """Basename that also splits Windows-style paths (``C:\\dir\\Game.exe``)."""
    s = token.strip().strip('"').strip("'")
    for sep in ("\\", "/"):
        if sep in s:
            s = s.rsplit(sep, 1)[-1]
    return s


def resolve_profile_for_argv(
    argv: list[str], settings: Settings
) -> GameProfile | None:
    """Find the enabled profile whose exe appears anywhere in *argv*."""
    names = {_basename(a).lower() for a in argv}
    lowered = " ".join(argv).lower()
    for profile in settings.enabled_profiles():
        if profile.match_mode == "exact" and profile.exe.lower() in names:
            return profile
        if profile.match_mode == "substring" and profile.exe.lower() in lowered:
            return profile
        if profile.match_mode == "regex":
            import re

            try:
                if any(re.search(profile.exe, a) for a in argv):
                    return profile
            except re.error:
                continue
    return None


def resolve_env_for_argv(argv: list[str], settings: Settings) -> dict[str, str]:
    profile = resolve_profile_for_argv(argv, settings)
    if profile is None:
        return {}
    env = dict(profile.env_assignments())
    # Make MangoHud actually load (the config file alone doesn't inject it).
    # Needed for the visible overlay AND for the frame-rate watchdog's CSV log.
    if profile.mangohud.get("enabled") or profile.fps_watchdog:
        env["MANGOHUD"] = "1"
        if profile.per_game_mangohud:
            from goblinmode.paths import MANGOHUD_DIR

            env["MANGOHUD_CONFIGFILE"] = str(MANGOHUD_DIR / f"{profile.exe}.conf")
    return env


def print_env_for(argv: list[str], settings: Settings) -> str:
    """Return newline-joined ``export K=V`` lines for the wrapper to ``eval``."""
    env = resolve_env_for_argv(argv, settings)
    return "\n".join(f"export {k}={shlex.quote(v)}" for k, v in sorted(env.items()))


def latest_log_files(limit: int = 8) -> list[Path]:
    if not GAME_LOG_DIR.exists():
        return []
    logs = sorted(
        GAME_LOG_DIR.glob("*.log"), key=lambda p: p.stat().st_mtime, reverse=True
    )
    return logs[:limit]
